### ISSUE TITLE
Code comments colour

### ISSUE THREAD

**Issue by onetrev** [hrsetyono/pacific-atom#1]
Great theme! Really do find it easy to work with so far. Just one thing I wondered. Totally feel free to shut down and close this, but any chance of just making the code comments a big brighter? I find it just a touch too close to the background. Thanks either way!

**Comment by hrsetyono** [comment]
Hi @onetrev 

Sorry for the late reply, must have missed this notification in my email.

I based this theme on one of Codecademy's course and tweak it here and there. The one I tweak the most is Comment, but it just doesn't feel right and always goes back to original color.

For me, I prefer Comment's color to distract less.

But feel free to fork it. Changing it is very easy since it's using LESS, a CSS that supports variable.

**Comment by onetrev** [comment]
No worries! Thanks for letting me know. And yes I can fork it or alternatively just add my own small edit to my styles.less file I believe would be the easiest way.
